Neufund/ico-transparency-monitor

package.json
src/index.js
yarn.lock

Tried to enable `redux-devtools-extension` I failed (issue will be created) but at least I cleaned a bit `index.js`.

Simplify store creation

---

src/config.js
src/utils.js

caching header no longer necessary -> switched to content based caching on nginx

Remove caching header

---

src/assets/css/App.css
src/components/Header.js
src/components/ICOApp.js
src/components/ICOScanHeader.js
src/config.js

rename add new ico link, remove the ehterscan link from ico app component and modify the links

Token links and modify etherscan links

---

package.json
src/actions/ModalAction.js
src/actions/ScanAction.js
src/actions/web3.js
src/assets/css/App.css
src/components/ICO.js
src/components/modals.js
src/reducers/modal.js
src/utils.js

It was impossible to do correctly without significant changes in code. But at least I fixed most obvious errors and cleaned code a bit.

Fix error handling

---

src/assets/css/App.css
src/components/ICOApp.js
src/components/ICOScan.js

1- Fix the status color.
2- Fix Responsive in "Submit new ICO"
3- add some more css

Responsive design

---

.babelrc
package.json
webpack.config.js
yarn.lock

set up explicit NODE_ENV during production build
remove `console.logs` in production build

Production related fixes

---

README.md

I added the part of 'Parity Node'

Readme parity part

---

src/assets/css/App.css

Just added a bolder border color when the user hover on the ICO Box.

add bolder border on ico box hover

---

src/components/details.js
test/components/ScanBoxDetails.details.test.js

giniIndex is no longer required

Fix PropTypes requirements in TokenDistribution component

---

src/assets/css/ScanBox.css
src/components/Header.js
src/components/ICOApp.js
src/components/ICOScan.js
src/components/ScanBoxDetails.js
src/components/details.js
src/config.js
src/utils.js
test/utils/utils.test.js
webpack.config.js

Word fixes

---

src/assets/css/App.css
src/components/Header.js
src/components/ICOApp.js
src/components/ICOScanHeader.js
src/components/modals.js

Change the transparency button styling according to the new design requirements.

transparency button styling

---

src/assets/css/App.css
src/components/ICOApp.js
src/config.js
test/components/ICOApp.test.js

Remove https from website view & make the white box more clear

---

src/actions/CurrencyAction.js
src/actions/web3.js
src/components/Error404.js
src/components/GroupButtons.js
src/components/RaisedAmount.js
src/containers/InnerIcoPage.js
src/containers/ScanBoxDetails.js
src/reducers/currency.js
src/utils.js
src/utils/stats.js
src/utils/web3.js
test/utils/utils.test.js

Adding ICO base currency

---

src/icos_config/status.js

Change logo path for status ICO

---

src/icos_config/neufund.js

Cap Format number

---

src/components/RaisedAmount.js
src/containers/ScanBoxDetails.js
src/icos_config/neufund.js
src/utils/stats.js

Add median ticket size

---

src/containers/ScanBoxDetails.js

Make ETH as default base currency for each ICO

Raised amount default currency

---

src/assets/css/App.css
src/containers/IcoDataRow.js

Better styles for ICOs links

---

src/assets/css/App.css
src/assets/css/ScanBox.css
src/components/Footer.js
src/components/ScanBoxLoadingMessage.js
src/components/TokenIssued.js

Adjust the mobile responsive page margin

---

src/containers/ScanBoxDetails.js
src/icos_config/jibrel.network.js
test/components/ScanBoxDetails.details.test.js

Fix Median function

---

src/assets/css/App.css
src/components/Header.js
src/components/ICOScanHeader.js
src/components/TopHeader.js
src/containers/IcoDataRow.js

Visual fixes part2

---

src/icos_config/filecoin.js

Change information for filecoin ico

---

src/components/Header.js

Change the name of the button to Join the discussion on BitcoinTalk

---

src/assets/css/App.css
src/containers/IcoDataRow.js

New design proposal

---

package.json
public/index.html
src/assets/css/ScanBox.css
src/components/Chart.js
src/components/ICOScanHeader.js
src/components/ShareButtons.js
src/containers/ScanBoxDetails.js
src/utils/charts.js
yarn.lock

Modify title of the picture.
Share button

Adding social media share buttons

---

src/assets/css/App.css
src/components/SearchBox.js
src/containers/IcosList.js
src/icos_config/index.js

Add search functions

---

src/icos_config/neufund.js

Move neufund date added

---

src/icos_config/greyp.js

provides end block of Greyp eto so whole dataset can be cached

seals greyp eto endblock
